from enum import Enum

class Gesture(Enum):
    NONE = 0
    RIGHT_INDEX_EXTENDED = 1
    RIGHT_INDEX_HOOK = 2
    RIGHT_INDEX_CLOSED = 3
    LEFT_INDEX_EXTENDED = 4
    LEFT_INDEX_HOOK = 5
    LEFT_INDEX_CLOSED = 6
    PINCH_IN = 7
    PINCH_OUT = 8
    THUMB_UP = 9
    THUMB_DOWN = 10
    EXTENDED_HAND_START = 11
    EXTENDED_HAND_END = 12
